const MOVIELIST = {
  LOADING: 'MOVIELIST_LOADING',
  FETCH_SUCCESS: 'MOVIELIST_FETCH_SUCCESS',
  FETCH_FAILED: 'MOVIELIST_FETCH_FAILED',
};

const PEOPLE = {
  FETCH_SUCCESS: 'PEOPLE_FETCH_SUCCESS',
  FETCH_FAILED: 'PEOPLE_FETCH_FAILED',
};

const PEOPLEDETAIL = {
  LOADING: 'PEOPLEDETAIL_LOADING',
  FETCH_DETAIL_SUCCESS: 'PEOPLEDETAIL_FETCH_DETAIL_SUCCESS',
  FETCH_DETAIL_FAILED: 'PEOPLEDETAIL_FETCH_DETAIL_SUCCESS',
  FETCH_ADD_POKEMON: 'PEOPLEDETAIL_FETCH_ADD_POKEMON'
}

export { MOVIELIST, PEOPLEDETAIL, PEOPLE };
